---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-alterconso
resources:
  # - namespace.yaml
  - external-secrets/regcred.yaml
  - external-secrets/s3-ovh.yaml
  - helm/repository.yaml
  - helm/release.yaml
  - image/repository.yaml
  - image/policy.yaml
  - image/updateautomation.yaml
  - backup.yaml