# .sops.yaml
creation_rules:
  # Règle spécifique par environnement
  - path_regex: applications/localhost/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu

  - path_regex: infrastructure/secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu