---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age-private-key
resources:
  - ../base/alterconso
  - ./alterconso/secrets.enc.yaml
patches:
  - path: alterconso/values.yaml
    target:
      kind: HelmRelease
      name: alterconso
  - target:
      kind: ImageUpdateAutomation
      name: alterconso
    patch: |
      - op: replace
        path: /spec/update/path
        value: ./apps/localhost