---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mkcert-ca
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kube-system-secret-store
  target:
    name: mkcert-ca
    template:
      type: opaque
  dataFrom:
    - extract:
        key: mkcert-ca