apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: k8up
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QLlpoZFTEPxKbBygpgzmRZyhZb44IEAVcTIoKF3/4ZUM/xCgVwRENGodrA==,iv:Wncv8P132YvN/zZDaIprzVgwae9+F5Lk/7RVg57K3LM=,tag:QzOUsUkp3aygabT2/I12gw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Px4piug84v0rcCokTI+nvRG3O/EK4kd6yiqTEOSmh1MOxwDOqt3yPbK8Wz4=,iv:5mU2jcZn4Os004IISYv4F14BSdSWy8w9sRcaIS/8AWw=,tag:teCvc4kCOrKN4zOBoqGF1A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:SzNjFkgosOjA2Be29BMh4Q==,iv:ZjWsakMIjvq9iZ96dDKlUgaeFH3SuIdwQOogumiCDqo=,tag:tQ94QiCeQTzNYrv57RDyug==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL3pMZGRhTGZweGZ4Vjl2
            QWtaWTNSVXBkWHBGdzFWd0NsZ0Q4TCtPUTBFCmFSTWtwc2M1NGRkRUJNaFV5WTAy
            SmtzcDhSSms1WHI2R29JTDJpNnJSQ2MKLS0tIGJ6UlNRN1dTVVNHZnk4a0RTSVVp
            Mml2R1p0R1BZVXdDdTczMUNxc0J3MU0KINq7iRD7AIty9kewhYGYXdKYDr9peXGi
            /YInYdkIAVYlBp0nwVT6PwgzaDZNNAZWKgmdLOcShxRayE6FvUqATw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:20:21Z"
    mac: ENC[AES256_GCM,data:GKLuZUjrSn+QpWOeMRDFBIdz/pQ1bJ9pHO/jXWMYm2zXfuXWuSx2weAi6gCm3F9Xkoo8Hg0abX8uEHg3QXwk2LlRRai55+wKEMUbWeuHig3xy9KMGxKHzJIWQm09rNoHmXCYbDkllmug9LGWROMKtXLgtOQvFdyYlH1GTuaJZuk=,iv:85a1CnYW8iizDpBxnqu+YYMWVMrN2IxDLqh+CCQef5c=,tag:c86qkfVvfJYnjWrypmUVdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
