apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: k8up
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WcZUKxUS8B2GsbvOMmF5V9SHiimgvdOmTQmw1IHHFHU5ksWqHjTMAKfwMdc=,iv:hYH8tjTkjYz1Yb5IH1SS1z4vi+h075yFzhdR9A0ti3M=,tag:LPuo6Xd7gY34vpEzHM6icw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1gYjGd0q9rjT3LG7F8RGNoL2ELjTbE8AadR+7sp4+IAKhJXulcp5zm7Stgc=,iv:idH0Rn2ICBdmtvcYXkjhlqdD0h4zyd9vNNUg/hzh/1I=,tag:8/BnU/ypNcBLZJufHLuinA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:mSnwkV/w8+3eEU94/c2HrQ==,iv:n0Q2U35dl2K4csz9R6+Z81GTVOgu2WGAOZWOU6L9+yQ=,tag:nZR653cMRb/ACHHbxj1hZA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QjlqcU85cExvcGgwbEo0
            YUpHUWlxcjBkSFpjaG9hQW5MQ3EyY09pQlY0CnppU0Z2cTFiQWllNVdqM3VjcEdy
            N25GUDNBMVBRT3VIS0VHTElLc2ZrYXMKLS0tIE5KZzliLzVobGlMQ2VvUUt5bFVZ
            L25QcmVRY3FsUW9RTXpZamFJb0Rra2MKPt8FWziKSS4Lpe16KY59kea+PBYdeMoi
            KMS/IQaxwwjlixSPnlQx6tZv3o0g6M7YpTiqB2Wpqmic7KIEnGEk5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:48:51Z"
    mac: ENC[AES256_GCM,data:BcmSeqO9gOECpJC2+DzZTXEN4nwW0m+tXYMhK2jEGrWHMCQae9mGBtSyB2xOkKYxvQE4ZF6MOdh+Hzo6V21l/ttJV3YW4MzsucdPqSRySyS+4Pr1PqVLIQN85qIPKGPNYMmm9Y5q0PrRe1GjMHJnd/OwztDX8y+37jAolLIGiI8=,iv:dbmhkWIHf2RPC2P3Hv0Y9p2SdGL1W7Bhejteyo8zRb8=,tag:D1o4nk/a4Vq3GgrizF8C0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
