apiVersion: v1
kind: Secret
metadata:
    name: ecolieu-mariadb
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:4Kxz5Ro=,iv:x4qtsj59vzQpSeJ11R61YDsKjYMsvQnEUpf8xPhiuDo=,tag:x90jZ1sAOHpcWUo7zdsufg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:3bMJGdnUOgy+rSGMbE0=,iv:otOfrX2lZG833DZcY3H4CdGSLzL1msRDrLev/9cpkQk=,tag:F+yN2o+hNlRyEdUQVSx33g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdGVIMFY5WTdlYVp3eG14
            dU1UZnh1cEtBUm1PMjloL3VZSExMM2k0T0FZCmZIRlR3VHRndzQwSjZIV2Jqb1lo
            Rm9kUm42OE5MbEtiVlpzUVBRTVFDdXcKLS0tIE10a3lQZHU1Z1ZQazYxYzk0VTZ5
            Rm5lSGpZUWxpSjNEZ3lSdU5lM1U5KzAKGNmY3M4EF3ovJ/sGrrPjvtweSaqsRZMQ
            75IsuBAAe9P3rACKCwo10IwGbBXp4J2AAIdGpUHk+x2DobsSD0/Vqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:23:14Z"
    mac: ENC[AES256_GCM,data:uKEqkxXyOQHga9zTm80XAKYWubBd0ttfJyHiUPcJis0NHP1X5OYfvkmNpXQ/tGnEp8O4xXwsLJLeKVdoIdaag65Rf4ggIlmruqFFMilONoak16tB3IX+cRPLvVJyK5tQkE5J3gB0edw8Ynear7WxKuKuORLI/s4IWJmnjjbBMBo=,iv:2/OZEl+xmS4/VioyHNpges0kT13AQLiQTFd8AgAaSH8=,tag:4N8alMS4cw5YrzYqhFV7Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ecolieu
stringData:
    wordpress-username: ENC[AES256_GCM,data:GKjIrdZbDvSUSQ==,iv:I8A+zQuvA3aYTCwKgAzcOyDejnhPUI8FUuiut/iI9Q4=,tag:WQ53LyYe9OsqV6txAguQXA==,type:str]
    wordpress-password: ENC[AES256_GCM,data:DNIbjasmDJD5QiMcnUI=,iv:+02PbJq33vkdAQuhY2jhI1mIJXe+OuZ0XeegOPxealA=,tag:qUSoPlw98Jp2MAoK4L1gdw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdGVIMFY5WTdlYVp3eG14
            dU1UZnh1cEtBUm1PMjloL3VZSExMM2k0T0FZCmZIRlR3VHRndzQwSjZIV2Jqb1lo
            Rm9kUm42OE5MbEtiVlpzUVBRTVFDdXcKLS0tIE10a3lQZHU1Z1ZQazYxYzk0VTZ5
            Rm5lSGpZUWxpSjNEZ3lSdU5lM1U5KzAKGNmY3M4EF3ovJ/sGrrPjvtweSaqsRZMQ
            75IsuBAAe9P3rACKCwo10IwGbBXp4J2AAIdGpUHk+x2DobsSD0/Vqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:23:14Z"
    mac: ENC[AES256_GCM,data:uKEqkxXyOQHga9zTm80XAKYWubBd0ttfJyHiUPcJis0NHP1X5OYfvkmNpXQ/tGnEp8O4xXwsLJLeKVdoIdaag65Rf4ggIlmruqFFMilONoak16tB3IX+cRPLvVJyK5tQkE5J3gB0edw8Ynear7WxKuKuORLI/s4IWJmnjjbBMBo=,iv:2/OZEl+xmS4/VioyHNpges0kT13AQLiQTFd8AgAaSH8=,tag:4N8alMS4cw5YrzYqhFV7Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
