apiVersion: v1
kind: Secret
metadata:
    name: ecolieu
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:sCkD2vmNHqPW9w==,iv:2iyneIelar0RBYd1MZGwnIc21XHH8xWi3bo4rppo4iM=,tag:TtHWUbBwuqWzWK2XU80Zvw==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:8iOz+evdtktIDpWibUk=,iv:NTJxckfCr+uolQvvLCAg5eyATw0YVNl8tkr2KUZya1s=,tag:6yRdxcfk4a/nNDwwEfU+eg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:/2CXedBLsOxG/w==,iv:nImultNl4nxfZflSyWrwfX2oIoPoSLLpZ///47ZgNZU=,tag:vYFsFf6EHR+PjInCO7T76g==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:KJgIFw9KcKGBTw==,iv:mlI0UuhPc97nrm1DmBx7Hz/ckCVydxagpgkBYfsWFuM=,tag:4xALFPRSVdJmj0FEVYFuJQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:mDXgfe876+tZMeMcoz8=,iv:10+iWXHbHMPs+L4bAOVE+We8mrFx2E9QUgPm90gpMZw=,tag:zIBYDdIXmpB8vlKFIkta8Q==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:0+BIolw=,iv:BXDhXrX3Z9VPs6jO0o007iDy4HDEobfOHgkC1AaPhw4=,tag:VOrG5o1MEJF17VrXYE179g==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSHEzeFk1UDE2SjlmRlha
            alJmcDZhQUZmRnNrN2J5ZmNjR3B6YnhnT2k4Cnh2OVVMMDhJVFA5eElrcUdmcW1H
            SUV3VW9qY21JN3NFS0dTMS9HWGIzeXcKLS0tIDdldC9sM0dxZDV1aXVGN281cUpF
            MDA5Tzk1Zy9aQVltcjRmRHk4YzRuS3MKFDYA06AXtRIanVVjpIb54tZash6rjrr8
            XIuR/2oqbdfA81TdjNZAcdN0QFF5JWjMk7oe+6nB0QIE6nngec7N3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T18:10:07Z"
    mac: ENC[AES256_GCM,data:RMkEXFLeiZinzIn5sbD+4mZe+xLlKKOV6XJVnw0CcQByBS8bXtACroBUZO5DZzc3vpOnExHCperTLxxQOTEk61Wr/QHFeos1OORG9RM7gZ2z2S/7k9wo8bZJIX6w2a0A7PFHK5vP4nWS45OcJJuw3q4y1n7cD8iV8XnPwhIXc3M=,iv:euUX3u/KArOqmkse01Gjq1a3xeXotW6LIyldCiDjU1E=,tag:kS7elEYGp4ednJQYvGvlgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
