apiVersion: v1
kind: Secret
metadata:
    name: ecolieu
stringData:
    WORDPRESS_USERNAME: ENC[AES256_GCM,data:WSiKfR36buZ8Tg==,iv:/Gn0ZqXqEzC2rwWR8E2uj4tlsM21q+DnDs9NaFeNnyQ=,tag:8VA2LvzC0cM+rRpdS59voQ==,type:str]
    WORDPRESS_PASSWORD: ENC[AES256_GCM,data:NzxIhF2g7tLdScajoxU=,iv:nxDWs0Mn9AdEG7QIE/ci2QIBQ3svOY1k8jpoVWsjqYs=,tag:4OLJEEFoliHGRbT9Fwd9zw==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZnFCRDluVGFVdnhTbjlt
            Yms1QVFFNUQ2VE1XeHh2TkRuRGhIL3NpdDNZClJKV3FxaDdRcXZQWnpWUGMvblg2
            RFJuU0FVdVB2TFE2UWV5T0REeTFwb2sKLS0tIFRlK1l2SUJzUUhvWUNFWGVobjVQ
            dnlJLzVrL1hzSzlpWCtVeXZvampWWDAKC80K0fBhiN/9L9ikS0v2XzFBfKn3PjPW
            fMcFer/5DC8nEaAIWFBPmbRZAB9FOQFEJpNv/X+Za2qpWdRviumALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:37:22Z"
    mac: ENC[AES256_GCM,data:aVga0VR2AIWAaaJp3Z6QjDiWsCZVhIh2nQePyvN9NUywUdWl2Oeku8fqGE4/HcllKGhLhpLHA5NiUh45gC8ToI/pNk2zAcD6LLQ3viJszQfO8XPds78pJkEETqdxmXifb/oqqnfXus3ywdsg4tM59rr7xPKDGnBlQQffLzmNJNc=,iv:eHAtWlIotCtAq9gigNhE/VnikOkg5t38TGbGWveSn0I=,tag:ZlUvwBheG2zgOkUydMY6bA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ecolieu-mariadb
stringData:
    MARIADB_USER: ENC[AES256_GCM,data:y2951iWPNvbsiQ==,iv:ee7hysD3/u5yJlDL4auxQQi+cJgD9824NJboYFGcA/8=,tag:IwOoVFFhHkF56N+RaE/Isg==,type:str]
    MARIADB_DATABASE: ENC[AES256_GCM,data:nvaiajlmzv4Hng==,iv:PqrZL7WxR76nk+fDY6HyycYiTBML/Wfnjz+nIrrW/ME=,tag:0TiJQbzxoc/1Wcy3ofzN7A==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:GoXUxZnyHatGwB50AAo=,iv:7p9h/B+IFMOj32M33m+KQb1zfl7qCkacjOwh32lfHbU=,tag:zk95SA4PGTGZfq41bmQlYw==,type:str]
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:tU51ooM=,iv:IA3ILsns2kjKno7Qa5iYukdbQ7G0u/M61gwuqDfdSos=,tag:lt/BIP0cXo2JZIlOn5cK5A==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZnFCRDluVGFVdnhTbjlt
            Yms1QVFFNUQ2VE1XeHh2TkRuRGhIL3NpdDNZClJKV3FxaDdRcXZQWnpWUGMvblg2
            RFJuU0FVdVB2TFE2UWV5T0REeTFwb2sKLS0tIFRlK1l2SUJzUUhvWUNFWGVobjVQ
            dnlJLzVrL1hzSzlpWCtVeXZvampWWDAKC80K0fBhiN/9L9ikS0v2XzFBfKn3PjPW
            fMcFer/5DC8nEaAIWFBPmbRZAB9FOQFEJpNv/X+Za2qpWdRviumALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:37:22Z"
    mac: ENC[AES256_GCM,data:aVga0VR2AIWAaaJp3Z6QjDiWsCZVhIh2nQePyvN9NUywUdWl2Oeku8fqGE4/HcllKGhLhpLHA5NiUh45gC8ToI/pNk2zAcD6LLQ3viJszQfO8XPds78pJkEETqdxmXifb/oqqnfXus3ywdsg4tM59rr7xPKDGnBlQQffLzmNJNc=,iv:eHAtWlIotCtAq9gigNhE/VnikOkg5t38TGbGWveSn0I=,tag:ZlUvwBheG2zgOkUydMY6bA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
# Secret associé
apiVersion: v1
kind: Secret
metadata:
    name: ecolieu-wordpress
type: Opaque
stringData:
    WORDPRESS_DATABASE_USER: ENC[AES256_GCM,data:b4bbA0naZW9AuQ==,iv:YpXP+YZ/b3ftbV6I5Ai5/RzUIPyma8tnil9XURoH6ys=,tag:8HoezquEfV1A1KHCl6u03Q==,type:str]
    WORDPRESS_DATABASE_PASSWORD: ENC[AES256_GCM,data:qFv7VetrY2bfkG/JSKQ=,iv:1xAamJltg3iYCnzJUxxsD87NkDUX6bMcz2dOx4ECywc=,tag:JYQekVDdSsLTFMJ7z91AZg==,type:str]
    WORDPRESS_DATABASE_NAME: ENC[AES256_GCM,data:rs2mPXfxtFXYhw==,iv:3OXEYXhVeRJQB3MFYFU4G5BI+Sg4IhkboaS7rW/yIIk=,tag:fFr6vOQb3o2/s55I8a+4HA==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZnFCRDluVGFVdnhTbjlt
            Yms1QVFFNUQ2VE1XeHh2TkRuRGhIL3NpdDNZClJKV3FxaDdRcXZQWnpWUGMvblg2
            RFJuU0FVdVB2TFE2UWV5T0REeTFwb2sKLS0tIFRlK1l2SUJzUUhvWUNFWGVobjVQ
            dnlJLzVrL1hzSzlpWCtVeXZvampWWDAKC80K0fBhiN/9L9ikS0v2XzFBfKn3PjPW
            fMcFer/5DC8nEaAIWFBPmbRZAB9FOQFEJpNv/X+Za2qpWdRviumALw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T19:37:22Z"
    mac: ENC[AES256_GCM,data:aVga0VR2AIWAaaJp3Z6QjDiWsCZVhIh2nQePyvN9NUywUdWl2Oeku8fqGE4/HcllKGhLhpLHA5NiUh45gC8ToI/pNk2zAcD6LLQ3viJszQfO8XPds78pJkEETqdxmXifb/oqqnfXus3ywdsg4tM59rr7xPKDGnBlQQffLzmNJNc=,iv:eHAtWlIotCtAq9gigNhE/VnikOkg5t38TGbGWveSn0I=,tag:ZlUvwBheG2zgOkUydMY6bA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
