apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-ecolieu
spec:
  values:
    wordpressUsername: ""
    wordpressPassword: ""
    wordpressEmail: dugrainamoudre@gmail.com
    mariadb:
      enabled: true
      auth:
        existingSecret: ecolieu-mariadb
    wordpressPlugins: []
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: le-portail.gpenaud.localhost
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: mkcert
      extraTls:
        - hosts:
            - le-portail.gpenaud.localhost
          secretName: le-portail.gpenaud.localhost-tls
  valuesFrom:
    - kind: Secret
      name: ecolieu
      valuesKey: wordpress-username
      targetPath: wordpressUsername
    - kind: Secret
      name: ecolieu
      valuesKey: wordpress-password
      targetPath: wordpressPassword
