apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: le-portail-ecolieu
spec:
  values:
    wordpressUsername: ""
    wordpressPassword: ""
    wordpressEmail: dugrainamoudre@gmail.com
    extraEnvVars:
      - name: WORDPRESS_DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: ecolieu-wordpress
            key: WORDPRESS_DATABASE_USER
      - name: WORDPRESS_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ecolieu-wordpress
            key: WORDPRESS_DATABASE_PASSWORD
      - name: WORDPRESS_DATABASE_HOST
        valueFrom:
          secretKeyRef:
            name: ecolieu-wordpress
            key: WORDPRESS_DATABASE_HOST
    mariadb:
      enabled: true
      auth:
        existingSecret: ecolieu-mariadb
    wordpressPlugins: []
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      hostname: le-portail.gpenaud.localhost
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: mkcert
      extraTls:
        - hosts:
            - le-portail.gpenaud.localhost
          secretName: le-portail.gpenaud.localhost-tls
  valuesFrom:
    - kind: Secret
      name: ecolieu
      valuesKey: WORDPRESS_USERNAME
      targetPath: wordpressUsername
    - kind: Secret
      name: ecolieu
      valuesKey: WORDPRESS_PASSWORD
      targetPath: wordpressPassword
