yamlapiVersion: v1
kind: Namespace
metadata:
  name: capsule-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: projectcapsule
  namespace: capsule-system
spec:
  interval: 24h
  url: https://projectcapsule.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capsule
  namespace: capsule-system
spec:
  interval: 30m
  chart:
    spec:
      chart: capsule
      version: "0.7.*"
      sourceRef:
        kind: HelmRepository
        name: projectcapsule
        namespace: capsule-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    manager:
      options:
        forceTenantPrefix: true
        capsuleUserGroups:
          - capsule.clastix.io
    replicaCount: 2