---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-secret
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://charts.clustersecret.com/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-secret
  namespace: kube-system
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: cluster-secret
      version: '0.4.3'
      sourceRef:
        kind: HelmRepository
        name: cluster-secret
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3