---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: le-portail-alterconso
resources:
  - ../../base/alterconso/
  - secrets.enc.yaml
  - backup-pod-config.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: alterconso
  - target:
      kind: ImageUpdateAutomation
      name: alterconso
    patch: |
      - op: replace
        path: /spec/update/path
        value: ./applications/le-portail/localhost
  - target: 
      kind: Schedule
      name: alterconso
    patch: |
      - op: add
        path: /spec
        value:
          podConfigRef:
            name: alterconso