apiVersion: v1
kind: Secret
metadata:
    name: alterconso-secrets
stringData:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:XVPP3a6YbKiPEw==,iv:WmGNHRtk9oeEOX1jDQLTYRwCAxSAp1Rn4JrmLXSHjgk=,tag:bZjJIJiIugNfS6InnFdpGQ==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:jcxTmzP/NOxXbg==,iv:VYZnADlx6RehzWVLC/W9O+TqUNyUehqhr2s8vX6JAmo=,tag:gImS1G6o+MSooifiAYNg+A==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeW9YM0g3Zk9Fc1ZQSHBQ
            SzJjMFFxQnNSbUxWT2x6VmN3emsyazRWYzFRClg0OXVmSzhxMXlKWjJnZVV3NFF5
            VUpSbEZ3d2k1Q0NCbzA3MjZjOW9hbmcKLS0tIGlMZHpUWXhnQXRiMW04MkR3cldV
            cHg1UHJBTENpOE1ESFgvYVFOcm1FL3cKcHhRT1zXB+UCqAaHhZTr8Wk1QTGvC+vA
            8u9jb+FVgJat9ISaV6NADxEwQTCkxWq0eSlaaKcfz6vsp4naoQhSug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T09:11:16Z"
    mac: ENC[AES256_GCM,data:nM/FLc9LFIPaISZuv5fgQYVl9Dtleuy7vx7uQuYLtmEfhKLnMaKeACcTZg3YHqlDxtWHMdUXMeojD/abil51mu4TtqUSpk9+shjcPCtKl3WrqncWAah+K6OQlVzbGbk7fpz7xmq1gLkoNTwImkhwOVQx7WvjxYS0nKByn9DaT+8=,iv:MKvz54xN9Ux9Y07WJ5Banq0+a6ce7d1Ql1UGwt6dLdU=,tag:ax8dbBz9mYHu5NQxHVf+SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
