apiVersion: v1
kind: Secret
metadata:
    name: alterconso-secrets
    namespace: alterconso
stringData:
    MYSQL_PASSWORD: ENC[AES256_GCM,data:KISN/+bNTjzQXQ==,iv:jFR8b0PLh9xLt4aaC4uYJAhJ/RxYLGpzayw8V1BgI6Y=,tag:l+6zkPAjq1YGDzsOW8cMaw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:cVnCqlvBIPtn+g==,iv:Nbobx2pIykhGnBjbdULd5+LgqrUeYWkVcKZKitq0iAY=,tag:6HavJzjuWhnWJomCCx9aZQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOXhUY2djSjRzUlJEeEVU
            YnVJb1IzSkhzc3ZlT3ovZTl2VXE2M09rTURjCkwwU0lDYWUrUkpiS1kyT3AxazJX
            VWJOTUlqSjhrb0NKaHU3L1YwdGJLd1kKLS0tIHpYcGVrZVVvb01IakFGVllMamYx
            eXlJZmkzK29QTm9tS3QwYVBZR3hZbEkKNOMSVhMOmU2V/pA3oKTXRPoeRbU6C8Hj
            2aF1Ekf0ThlqNnVpqjHWDkkUT+U+2/rXlEYv24iOS37kuWo2b6jk8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T09:35:39Z"
    mac: ENC[AES256_GCM,data:XFHJ8pY8f6nTnEvT4KonO8H4C71+sLH133+Dr7oeuImQYNV5IkKTfWe3SEzumJoM1FKl36RdPLnP4RzSCZYuY4MqcQ4QC0SDlvJWty320NxhNH0OynehnM7kgNsSVQUB6a9uUJEl7Vi6TtIDzS95XGOlqz+wjJk6vxW+mxgwKPo=,iv:7tp0teAlC/Gv2Bs3pZO+j4HPlfUfOfyU4C8f8M47Ea0=,tag:zCB+0ALr1Z9ecm7HUsUgvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
