---
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: alterconso
  namespace: alterconso
spec:
  template:
    spec:
      containers:
        - name: backup
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 1000
            runAsGroup: 1000