---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/alterconso
  - secrets.enc.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: alterconso
  - target:
      kind: ImageUpdateAutomation
      name: alterconso
    patch: |
      - op: replace
        path: /spec/update/path
        value: ./applications/localhost