---
apiVersion: v1
kind: Secret
metadata:
    name: alterconso
    namespace: alterconso
stringData:
    MYSQL_USER: ENC[AES256_GCM,data:yKCDWmPShJbD3Q==,iv:aU1B2rMe25jKpN8m2lW0XzPKpsUYc+kGnFgSeJu3Vs8=,tag:1t1dELfh4Ub9gBqIhKqC6A==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:XtrIePeKtMhXqZNjD1U=,iv:eUCdpndajHMJU8Oc0l035AGUm+js45JMhJ5hnNU4N2U=,tag:pxbGuorv88MAV8VumdQCgg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:I5P/MFsQcpDejOaplg==,iv:sa6P3IrGRVcyxg/ygoxPQhDyMdnijVQSFbFJrcIoR/4=,tag:QHw/Ug5aDBnzt4B9TOHT4A==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:C89mrBlW/lyw8A==,iv:VTmCx3KcLV1xpUIPKfjx9hleuwPfn4UccOdmGvvPJ+c=,tag:L0lxppktWlQwDVOmjueABQ==,type:str]
sops:
    age:
        - recipient: age126qcg2kflqz4tdw3humcl6a0ddp8e685lqst6pattugtrwj57ehqma5dnu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q1dYanhicUdMd1Q3Vk1N
            dkpBV0FJUS9FcjltYWRlblJtcU5GOUpQR2lVCm1lYmxIbEFRNFhxMWExcStHZFJz
            eTFpc29nMXY4NS9xY3N1VERvWGNCL00KLS0tIG1NQUNxMWQ1Wi9xMWhvNHR5aHNC
            NlE1cUdubGkvaDczOXQ5NlFHdzhCVzgK5kH930hFRtHHmW62V3Q8lrKOmdNrrX18
            opHA935m20a7X4SpBPAobmUVALZEXwzE4R3jcfSLCMkt0V0rPZPu4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T09:01:44Z"
    mac: ENC[AES256_GCM,data:BMIdggauvwY9NxIn9rq9pNmjYO3XGwJ5Z4SbtN3ILI3o4bJEPsgWrGdVRafx4vy4H9UrcMZ8sTcZiAj+TnvfPg/6FmO58hQ9B5SHoBRewWnw3AkDRWLFuIl+xTUzYssAHk6JL26gqZ8mxA+nIhrLEW6r0Wu8daxKACcBp15tpdU=,iv:xBQPu2H5PjyM8Mj6KwqAz3r734JwpgwqhhB6gnXBowE=,tag:+B9QJrabMgHwiXrIdDyCPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
