apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: wordpress
spec:
  backend:
    repoPasswordSecretRef:
      name: s3-ovh
      key: RESTIC_PASSWORD
    s3:
      endpoint: https://s3.sbg.io.cloud.ovh.net 
      bucket: le-portail-alterconso-backups
      accessKeyIDSecretRef:
        name: s3-ovh
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: s3-ovh
        key: AWS_SECRET_ACCESS_KEY
  backup:
    schedule: '0 21 1,15 * *'   # 1er et 15 de chaque mois à 21h
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 3
  check:
    schedule: '30 21 1,15 * *'  # vérification 30min après
  prune:
    schedule: '0 22 1,15 * *'   # nettoyage 1h après
    retention:
      keepWeekly: 8              # ~4 mois de rétention
      keepMonthly: 6